language: android
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  global:
  - ADB_INSTALL_TIMEOUT=10
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
android:
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  components:
  - tools
  - platform-tools
  # The BuildTools version used by your project
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  # The SDK version used to compile your project
  - android-$ANDROID_API_LEVEL
  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - android-19
  - sys-img-armeabi-v7a-android-19
  - android-21
  - sys-img-armeabi-v7a-android-21
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/daemon
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper
before_script:
- chmod +x gradlew
- android list targets
- echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
script:
- android-wait-for-emulator
- adb devices
- adb shell input keyevent 82 &
- ./gradlew testDebugUnitTest installDebug